// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {orderedmap} from '../models';

export function InitializeRythmContext(arg1:data.CandleHistory,arg2:number,arg3:orderedmap.OrderedMap[int,int]):Promise<void>;
