// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {data} from '../models';

export function CloseStream():Promise<void>;

export function CreateCandle(arg1:time.Time,arg2:number,arg3:number,arg4:number,arg5:number):Promise<data.Candle>;

export function ExportCandleHistory():Promise<Array<data.FrontEndCandle>>;

export function Greet(arg1:string):Promise<string>;

export function OpenStream():Promise<Array<data.FrontEndCandle>>;
