// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseStream() {
  return window['go']['main']['App']['CloseStream']();
}

export function CreateCandle(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateCandle'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportCandleHistory() {
  return window['go']['main']['App']['ExportCandleHistory']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenStream() {
  return window['go']['main']['App']['OpenStream']();
}
